// <auto-generated>
// GENERATED by tools/textures/build_textures.py from tools/textures/textures.config.
// Maps a WebContentManager texture key (ResolvePath output, e.g. "Content/gfx/sprites/x")
// to the precompiled sibling extension shipped for it. WebContentManager.LoadTexture probes
// ONLY the listed sibling; an unlisted key skips straight to the .png (no failing .dds/.rtex
// OpenStream probes + thrown exceptions). Re-run build_textures.py after editing textures.config;
// do NOT hand-edit this file.
// </auto-generated>
using System.Collections.Generic;

namespace EvilAliensWeb.Compat
{
    internal static class PrecompiledTextures
    {
        public static readonly Dictionary<string, string> Siblings = new Dictionary<string, string>
        {
            { "Content/gfx/sprites/spider_sheet2", ".dds" },
            { "Content/gfx/sprites/large_asteroid", ".rtex" },
            { "Content/gfx/sprites/brainanimated", ".dds" },
            { "Content/gfx/sprites/brainanimatedglow", ".rtex" },
            { "Content/gfx/game/space/space00", ".dds" },
            { "Content/gfx/game/space/space01", ".dds" },
            { "Content/gfx/game/space/space02", ".dds" },
            { "Content/gfx/game/space/space03", ".dds" },
            { "Content/gfx/game/space/space04", ".dds" },
            { "Content/gfx/game/space/space05", ".dds" },
            { "Content/gfx/game/space/space06", ".dds" },
            { "Content/gfx/game/space/space07", ".dds" },
            { "Content/gfx/game/space/space08", ".dds" },
            { "Content/gfx/game/space/space09", ".dds" },
            { "Content/gfx/game/space/space10", ".dds" },
            { "Content/gfx/game/space/space11", ".dds" },
        };
    }
}
